name: appwrite
version: 9.0.0+oauthfix
description: Appwrite Flutter SDK (legacy deps + OAuth fix)
environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

  cookie_jar: ^4.0.8
  http: '>=0.13.6 <2.0.0'
  web_socket_channel: ^3.0.1
  path_provider: ^2.1.4

  web: '>=0.5.0 <=0.6.0'
  package_info_plus: '>=6.0.0 <7.0.0'
  device_info_plus: '>=9.0.0 <11.0.0'

  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter